sudo: required
services:
    -docker

before_install:
    - docker build -f Dockerfile.dev -t bingani/docker-react .

script:
    - docker run -e CI=true bingani/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-779195591143"
    bucket_patch: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY